name: Continuous Integration
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        id: clippy-check
        name: Check project against Clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - id: prepare-tests
        name: Prepare test environment (Kafka)
        run: docker-compose -f "docker-compose.yml" up -d --build

      - id: install-tarpaulin
        name: Install Cargo tarpaulin
        run: cargo install tarpaulin

      - id: test-coverage
        name: Run tests with coverage
        run: cargo tarpaulin --verbose --all-features --no-fail-fast --out Xml

      - id: teardown
        name: Tear down test environment
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true

      - id: docker-build
        name: Build release using Docker
        run: docker build .
